// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANocTe71LmmQZqY_xo08Zs9L0YsztxGyU',
    appId: '1:347145817860:web:4fd59997b97d9ff234ca51',
    messagingSenderId: '347145817860',
    projectId: 'dev-dockflow',
    authDomain: 'dev-dockflow.firebaseapp.com',
    storageBucket: 'dev-dockflow.firebasestorage.app',
    measurementId: 'G-0YJ16JBM7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXmgli6pW6JZlKSCIgM8WWZnAL6qvQxFk',
    appId: '1:347145817860:android:28eaa98da1fa29f334ca51',
    messagingSenderId: '347145817860',
    projectId: 'dev-dockflow',
    storageBucket: 'dev-dockflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlSwwBQsJb2jPv5-MpBA_HPVprSJhsn4s',
    appId: '1:347145817860:ios:45f46435ceddb38c34ca51',
    messagingSenderId: '347145817860',
    projectId: 'dev-dockflow',
    storageBucket: 'dev-dockflow.firebasestorage.app',
    iosBundleId: 'com.example.dockFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlSwwBQsJb2jPv5-MpBA_HPVprSJhsn4s',
    appId: '1:347145817860:ios:45f46435ceddb38c34ca51',
    messagingSenderId: '347145817860',
    projectId: 'dev-dockflow',
    storageBucket: 'dev-dockflow.firebasestorage.app',
    iosBundleId: 'com.example.dockFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANocTe71LmmQZqY_xo08Zs9L0YsztxGyU',
    appId: '1:347145817860:web:805ee9039d590ee534ca51',
    messagingSenderId: '347145817860',
    projectId: 'dev-dockflow',
    authDomain: 'dev-dockflow.firebaseapp.com',
    storageBucket: 'dev-dockflow.firebasestorage.app',
    measurementId: 'G-4KBWS8PZPL',
  );
}
