// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVRyUO8psTy5XtFYmF__RvZe8N9FKta1g',
    appId: '1:699017081583:web:e65ba00437e760f534a11a',
    messagingSenderId: '699017081583',
    projectId: 'dockflow-cd84e',
    authDomain: 'dockflow-cd84e.firebaseapp.com',
    storageBucket: 'dockflow-cd84e.firebasestorage.app',
    measurementId: 'G-6BSS8K07DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffXVSrmWj7UIUMehye6W66Pu9_T-zQrI',
    appId: '1:699017081583:android:de062f1996807b3c34a11a',
    messagingSenderId: '699017081583',
    projectId: 'dockflow-cd84e',
    storageBucket: 'dockflow-cd84e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDlX1hUHPiysQN9OyQggmZ_N5wIT8od30',
    appId: '1:699017081583:ios:9a2d835b48dc895f34a11a',
    messagingSenderId: '699017081583',
    projectId: 'dockflow-cd84e',
    storageBucket: 'dockflow-cd84e.firebasestorage.app',
    iosBundleId: 'com.example.dockFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDlX1hUHPiysQN9OyQggmZ_N5wIT8od30',
    appId: '1:699017081583:ios:9a2d835b48dc895f34a11a',
    messagingSenderId: '699017081583',
    projectId: 'dockflow-cd84e',
    storageBucket: 'dockflow-cd84e.firebasestorage.app',
    iosBundleId: 'com.example.dockFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVRyUO8psTy5XtFYmF__RvZe8N9FKta1g',
    appId: '1:699017081583:web:9126246026f1643b34a11a',
    messagingSenderId: '699017081583',
    projectId: 'dockflow-cd84e',
    authDomain: 'dockflow-cd84e.firebaseapp.com',
    storageBucket: 'dockflow-cd84e.firebasestorage.app',
    measurementId: 'G-PQSTS440XM',
  );

}